# Parking Space Variables
# Charging rates in kW
from functools import reduce

DISCOUNT = 1.0
VEHICLE_BATTERY_CAPACITY = 60.0
VEHICLE_MIN_CHARGE = 0.0
MAX_CHARGING_RATE = 20.0
MAX_DISCHARGING_RATE = 20.0
AVG_CHARGING_RATE = 10
BATTERY_CAPACITY = 60



NUM_OF_ACTIONS = 8

NUMBER_OF_AGENTS = 12
MAX_BUFFER_SIZE = 100000

EPSILON = 0.2
EPSILON_DECAY_RATE = 0.98
EPSILON_DECAY_PERIOD = 24
NEW_EPSILON_STARTING_STEPS = 24
# EPSILON_RESTART_PERIOD = 480

EPSILON_TRAIN_AGENT = True
# EPSILON_TRAIN_AGENT = False
# SINGLE_EPSILON = True
SINGLE_EPSILON = False
# EPSILON_COMBINATIONS = True
EPSILON_COMBINATIONS = False

CRID_COEFFICIENT = 0.8
GARAGE_LIST = []
# AVG_CONSUMPTION = lambda : reduce(lambda x, y: x + y, GARAGE_LIST, 0.0) * AVG_CHARGING_RATE

# TRAIN_ITERATIONS = 24 * 100 * 500
TRAIN_ITERATIONS = 10

NUM_EVAL_EPISODES = 20

# EAGER_EXECUTION = True
EAGER_EXECUTION = False

# USE_JIT = True
USE_JIT = False

# EVAL_PRETRAINED_NETWORKS = True
EVAL_PRETRAINED_NETWORKS = False

EVAL_ONLY = True
# EVAL_ONLY = False

# RECORD_EVAL = True
RECORD_EVAL = False

# EVAL_STATIC_STRATEGY = True
EVAL_STATIC_STRATEGY = False

# SCALE_BIAS = True
SCALE_BIAS = False

KEEP_BEST = True
# KEEP_BEST = False

# RECORD_TRAIN_EVAL = True
RECORD_TRAIN_EVAL = False

START_FROM_BEST = True
# START_FROM_BEST = False

# START_FROM_PREVIOUS = True
START_FROM_PREVIOUS = False

# START_FROM_SCRATCH = True
START_FROM_SCRATCH = False

# LOAD_BEST_PRETRAINED_MODEL = True
LOAD_BEST_PRETRAINED_MODEL = False

# PLOT_ACTIONS_SUM = True
# PLOT_ACTIONS_SUM = False
# PLOT_PRETRAINED_NETWORK = True
PLOT_PRETRAINED_NETWORK = False

PLOT_SMART_POLICY = True
# PLOT_SMART_POLICY = False

CHECKPOINT_FOLDER = 'checkpoints_3'
# CHECKPOINT_FOLDER = 'checkpoints_8'

# PLOTS_FOLDER = 'plots'
PLOTS_FOLDER = 'plots_2'

TRAIN_PRICES_FILE = 'data/data_sorted_by_date.csv'
# TRAIN_PRICES_FILE = 'data/eval_data.csv'

EVAL_PRICES_FILE='data/eval_data_20_days.csv'
# EVAL_PRICES_FILE='data/eval_data.csv'
# EVAL_PRICES_FILE='data/data_sorted_by_date.csv'